#page title
page_title                                : tankste! - Deine Tankpreis App                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1633457177                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : de                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/de/app/tankste-deine-tankpreis-app/id1633457177                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=app.tankste # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : tankste! - Deine Tankpreis App                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Kostenlos                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Finde die günstigste Tankstelle in deiner Nähe!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Fabian Keunecke
your_link                                 : https://fabiankeunecke.de/
your_city                                 : Germany
email_address                             : hello@tankste.app
facebook_username                         :                                           
instagram_username                        : tankste.app
twitter_username                          : tankste_app
github_username                           : tankste
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Ampelsystem
    description                           : Mit dem bereits bekannten Ampelsystem seht ihr auf einen Blick an welchen Tankstellen das Benzin oder der Diesel aktuell günstig ist.
    fontawesome_icon_name                 : traffic-light

  - title                                 : Filter
    description                           : Mit den einfachen Filtermöglichkeiten, kannst du die Spritsorte deiner Wahl auswählen. Du kannst zwischen Benzin E5, Benzin E10 und Diesel auswählen.
    fontawesome_icon_name                 : search

  - title                                 : Tschüss Bertha
    description                           : Unsere Lieblings-App Bertha wird leider nicht mehr angeboten, und andere Apps überzeugten uns nicht. Also kamen wir zu dem Entschluss, das minimalistische Design der ehmaligen App zu übernehmen und mit tankste! ein ähnliches Nutzererlebnis anzubieten.
    fontawesome_icon_name                 : rocket

  - title                                 : Open Source
    description                           : Da wir nicht möchten, dass die Idee hinter Bertha erneut verloren geht, ist das Projekt komplett Quelloffen. Ihr findet den Code auf Github, und könnt so an dem Projekt mitarbeiten. Euch fehlt eine Funktion? Kein Problem! Einfach einen Pull Request oder ein Issue erstellen.
    fontawesome_icon_name                 : code

  - title                                 : Mehr Funktionen
    description                           : Währen wir in unserer ersten Version nur ein kleines Funktionset anbieten, könnt ihr euch für die Zukunft bereits auf mehr freuen! 
    fontawesome_icon_name                 : star

# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1
topbar_title_color                        : "#000000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#9253a4"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#9253a4"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#9253a4"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#9253a4"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
